name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no ziprnorge@35.190.205.208 "echo 'SSH connection successful'"

      - name: Deploy code
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          ssh -o StrictHostKeyChecking=no ziprnorge@35.190.205.208 '
          export NODE_OPTIONS=--openssl-legacy-provider &&
          git config --global --add safe.directory /var/www/seesvee &&
          cd /var/www/seesvee &&
          git pull &&
          npm install &&
          npm run build &&
          pm2 stop seesvee-backend || true &&
          pm2 delete seesvee-backend || true &&
          pm2 start server.js --name seesvee-backend
          '
